In [1]:
import pandas as pd

## Add MRD1 (pupil to upper)

In [2]:
df = pd.read_csv("eye_frames_20250414_124415/eye_measurements.csv")
df.head()

,timestamp,frame,left_palpebral_height,left_pupil_to_lower,right_palpebral_height,right_pupil_to_lower
0,-0.033333,0,98.045908,49.162994,94.339811,51.623638
1,0.016667,1,100.019998,50.159745,94.260278,52.201533
2,0.083333,3,101.123687,50.089919,95.634722,50.000000
3,0.100000,4,99.020200,49.365980,94.339811,51.244512
4,0.116667,5,102.004902,50.249378,93.343452,49.335586

In [3]:
df['right_pupil_to_upper'] = df['right_palpebral_height'] - df['right_pupil_to_lower']
df['left_pupil_to_upper'] = df['left_palpebral_height'] - df['left_pupil_to_lower']

In [4]:
df.head()

,timestamp,frame,left_palpebral_height,left_pupil_to_lower,right_palpebral_height,right_pupil_to_lower,right_pupil_to_upper,left_pupil_to_upper
0,-0.033333,0,98.045908,49.162994,94.339811,51.623638,42.716173,48.882913
1,0.016667,1,100.019998,50.159745,94.260278,52.201533,42.058745,49.860253
2,0.083333,3,101.123687,50.089919,95.634722,50.000000,45.634722,51.033767
3,0.100000,4,99.020200,49.365980,94.339811,51.244512,43.095299,49.654220
4,0.116667,5,102.004902,50.249378,93.343452,49.335586,44.007866,51.755524

In [5]:
df.drop(columns=['right_pupil_to_lower', 'left_pupil_to_lower'], inplace=True)

In [6]:
df.head()

,timestamp,frame,left_palpebral_height,right_palpebral_height,right_pupil_to_upper,left_pupil_to_upper
0,-0.033333,0,98.045908,94.339811,42.716173,48.882913
1,0.016667,1,100.019998,94.260278,42.058745,49.860253
2,0.083333,3,101.123687,95.634722,45.634722,51.033767
3,0.100000,4,99.020200,94.339811,43.095299,49.654220
4,0.116667,5,102.004902,93.343452,44.007866,51.755524

In [7]:
df['timestamp'] -= df['timestamp'].iloc[0]
df.head()

,timestamp,frame,left_palpebral_height,right_palpebral_height,right_pupil_to_upper,left_pupil_to_upper
0,0.000000,0,98.045908,94.339811,42.716173,48.882913
1,0.050000,1,100.019998,94.260278,42.058745,49.860253
2,0.116667,3,101.123687,95.634722,45.634722,51.033767
3,0.133333,4,99.020200,94.339811,43.095299,49.654220
4,0.150000,5,102.004902,93.343452,44.007866,51.755524

In [8]:
len(df)

188

In [9]:
df.to_csv("eye_frames_20250414_124415/actual_eye_measurements.csv", index=False)

In [10]:
new_df = pd.read_excel("eye_frames_20250414_124415/avneesh_annotated.xlsx")
new_df.to_csv("eye_frames_20250414_124415/avneesh_annotated.csv", index=False)